(() => {
  const $ = (s, root=document) => root.querySelector(s);
  const allArticles = [...(window.ARTICLES || [])];
  const localKey = 'nayadaur-local-articles';
  const getLocal = () => { try { return JSON.parse(localStorage.getItem(localKey) || '[]'); } catch { return []; } };
  const all = () => [...getLocal(), ...allArticles];
  const esc = (v='') => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const slugify = s => s.toLowerCase().trim().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-') || `article-${Date.now()}`;
  const formatDate = d => new Date(`${d}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
  const card = a => `<article class="article-card"><a class="card-visual" href="article.html?slug=${encodeURIComponent(a.slug)}" ${a.image ? `style="background-image:url('${esc(a.image)}')"` : ''}><span class="card-category">${esc(a.category)}</span><span class="card-arrow">↗</span></a><div class="card-content"><div class="card-meta"><span>${esc(formatDate(a.date))}</span><span>•</span><span>${esc(a.readTime)}</span></div><h3><a href="article.html?slug=${encodeURIComponent(a.slug)}">${esc(a.title)}</a></h3><p>${esc(a.excerpt)}</p><a class="read-link" href="article.html?slug=${encodeURIComponent(a.slug)}">Read article <span>→</span></a></div></article>`;
  const setupTheme = () => { const btn=$('#themeToggle'); if(!btn)return; const saved=localStorage.getItem('nayadaur-theme'); if(saved==='dark')document.documentElement.dataset.theme='dark'; btn.addEventListener('click',()=>{const dark=document.documentElement.dataset.theme==='dark'; document.documentElement.dataset.theme=dark?'':'dark'; localStorage.setItem('nayadaur-theme',dark?'light':'dark');}); };
  const renderHome = () => { const grid=$('#articleGrid'); if(!grid)return; const input=$('#searchInput'), empty=$('#emptyState'); const render=()=>{const q=(input?.value||'').toLowerCase().trim(); const rows=all().filter(a=>!q || [a.title,a.excerpt,a.category].join(' ').toLowerCase().includes(q)); grid.innerHTML=rows.map(card).join(''); empty.hidden=rows.length>0;}; input?.addEventListener('input',render); render(); const cats=[...new Set(all().map(a=>a.category))]; const list=$('#categoryList'); if(list)list.innerHTML=cats.map(c=>`<a href="#latest" class="category-chip" data-category="${esc(c)}"><span>${esc(c)}</span><span>↗</span></a>`).join(''); list?.addEventListener('click',e=>{const chip=e.target.closest('[data-category]'); if(!chip)return; e.preventDefault(); if(input){input.value=chip.dataset.category; render(); location.hash='latest';}}); };
  const renderArticle = () => { const root=$('#articleRoot'); if(!root)return; const slug=new URLSearchParams(location.search).get('slug'); const a=all().find(x=>x.slug===slug) || all()[0]; if(!a){root.innerHTML='<h1>Article not found</h1>'; return;} document.title=`${a.title} — NayaDaur`; root.innerHTML=`<div class="article-header"><span class="card-category">${esc(a.category)}</span><h1>${esc(a.title)}</h1><p class="article-excerpt">${esc(a.excerpt)}</p><div class="card-meta"><span>${esc(formatDate(a.date))}</span><span>•</span><span>${esc(a.readTime)}</span></div></div>`; const body=$('#articleBody'); body.innerHTML=(a.body||[]).map(p=>`<p>${esc(p)}</p>`).join(''); };
  const renderSaved = () => { const list=$('#savedList'); if(!list)return; const rows=getLocal(); list.innerHTML=rows.length ? rows.map(a=>`<div class="saved-item"><div><b>${esc(a.title)}</b><small>${esc(a.category)} · ${esc(a.date)}</small></div><button class="delete-draft" data-slug="${esc(a.slug)}" type="button">Delete</button></div>`).join('') : '<p class="empty-state">No local drafts yet.</p>'; list.onclick=e=>{const b=e.target.closest('.delete-draft');if(!b)return;localStorage.setItem(localKey,JSON.stringify(getLocal().filter(a=>a.slug!==b.dataset.slug)));renderSaved();}; };
  const setupEditor = () => { const form=$('#articleForm'); if(!form)return; const msg=$('#formMessage'); const fields={title:$('#title'),category:$('#category'),readTime:$('#readTime'),excerpt:$('#excerpt'),image:$('#image'),body:$('#body')}; form.addEventListener('submit',e=>{e.preventDefault();const a={slug:slugify(fields.title.value),title:fields.title.value.trim(),category:fields.category.value,readTime:fields.readTime.value.trim()||'4 min read',excerpt:fields.excerpt.value.trim(),image:fields.image.value.trim(),date:new Date().toISOString().slice(0,10),body:fields.body.value.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean)};const rows=getLocal().filter(x=>x.slug!==a.slug);rows.unshift(a);localStorage.setItem(localKey,JSON.stringify(rows));msg.textContent='Article saved in this browser. Export articles.js before publishing.'; form.reset();fields.readTime.value='4 min read';renderSaved();}); $('#clearDraft')?.addEventListener('click',()=>{form.reset();fields.readTime.value='4 min read';msg.textContent='Form cleared.';}); $('#exportBtn')?.addEventListener('click',()=>{const merged=[...getLocal(),...allArticles];const text='window.SITE_CONFIG = '+JSON.stringify(window.SITE_CONFIG||{},null,2)+';\nwindow.ARTICLES = '+JSON.stringify(merged,null,2)+';\n';const blob=new Blob([text],{type:'text/javascript'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='articles.js';a.click();URL.revokeObjectURL(url);msg.textContent='articles.js downloaded.';});renderSaved(); };
  setupTheme(); renderHome(); renderArticle(); setupEditor();
})();